### PR TITLE
Access level tests

### PR DESCRIPTION
**Pull request by skrchnavy**
Added tests using behat to verify that checks for access level are correct in  different methods.

(be aware that this depends on PR #100 , branch was created from branch in that PR)

### CODE REVIEW

**Comment by skrchnavy** [comment]
Master merged into this branch with changes in PR #123.
@mlespiau / @RussH  please review these changes.

**Comment by skrchnavy** [comment]
@RussH / @mlespiau  are there any comments to this PR? only tests were added to cover current functionality.

**Comment by mlespiau** [comment]
Hi @skrchnavy the reason why I did not merge is that security tests are failing on my computer. I've tried to understand why but could not find the reason :(. 
I'm manually following the steps done by the travis script.

**Comment by skrchnavy** [comment]
@mlespiau please check database initialization part, you need probably other data to be included in DB (special users).

**Comment by mlespiau** [comment]
Hi @skrchnavy. Found the reason for failing tests. Made a suggestion on SecurityContext.php file. Will merge if accepted.

**Comment by RussH** [comment]
Any update on this, guys?

**Comment by skrchnavy** [comment]
@mlespiau I can't find any change in SecurityContext.php.

**Comment by skrchnavy** [comment]
tests were updated after merge of master (based on request in commit 4b3b61231871f33e3a905e2a2794ae094519cd8b )
Is there any blocking issue for merging this PR?

**Comment by mlespiau** [comment]
Hi @skrchnavy you can see the comments in the "files changed" tab on this PR, I've added new comments mentioning you.

**Comment by skrchnavy** [comment]
@mlespiau I don't see there any comments in ;files changed' tab. I don't understand how to enable them or what shall I do. Isn't it caused by not proper type of comment (review type)?
@RussH  do you see any comment?

**Comment by RussH** [comment]
I can see where comments would have been made..

​[image: Inline images 1]​


​But I can't see where the comments will show-up afterwards!​


----
Russ

**Comment by mlespiau** [comment]
image

**Comment by skrchnavy** [comment]
regarding the commented settings actions, it was done because in the code there seemed not to be any call.
I found this strange code: https://github.com/opencats/OpenCATS/blob/master/modules/login/LoginUI.php#L408
where is wrong end comment. It comes from initial import into repo and not sure how it works, i PHP was able to understand ```* /``` last comment or really ignored the code.

**Comment by skrchnavy** [comment]
@mlespiau your comments accepted and code corrected

**Comment by skrchnavy** [comment]
have to comment some tests that were not working due to other way of access level checks. I am not sure if in current code base we are able to test them properly without big effort.

**Comment by mlespiau** [comment]
> have to comment some tests that were not working due to other way of access level checks. I am not sure if in current code base we are able to test them properly without big effort.

Are they going to be properly tested once you merge the other changes?

**Comment by skrchnavy** [comment]
The functionality skipped in tests is used mostly during installation. it is related to ```modules/settings/SettingsUI.php``` where are missing checks for user.
You can test in latest release access to index.php?m=settings&a=newInstallFinished and it allows you to access the page, what is error in implementation.

With PR #91 there is better chance to fix this issue and pass thise tests.

**Pull request merged**
