### PR TITLE
Ckeditor font plugin only where needed

### PR DESCRIPTION
**Pull request by skrchnavy**
font plugin in ckeditor is not for in common ckeditor config but is added into CKEDITOR instance creation.

### CODE REVIEW

**Comment by skrchnavy** [comment]
Tested and it works as before on the pages where is expected (Add/Edit job order , send email)

**Comment by skrchnavy** [comment]
#257 was merged and font plugin configured in config.js in CK editor then disappeared. This PR returns back font plugin in instances of CK editor

**Comment by skrchnavy** [comment]
comments addressed, ckeditor-manager.js added

**Comment by mlespiau** [comment]
Hi @skrchnavy thanks for addressing the comments! Great job! :)

**Pull request merged**
