### PR TITLE
adding php version currently under active support tot the test matrix

### PR DESCRIPTION
**Pull request by attachmentgenie**
also fixed an indentation problem in .travis.yml that caused the file to not be read into travis anymore

### CODE REVIEW

**Comment by RussH** [comment]
@attachmentgenie did you expect this to build under travis?

**Comment by attachmentgenie** [comment]
> @attachmentgenie I appreciate the PR but did you expect this to build sucessfully under travis, as it's failing

i didnt since that was already broken beforehand, but i fixed it in my subsequent commits. I also bumped the docker compose version to $latest and fixed the php 7.4 deprecation warnings

**Comment by RussH** [comment]
Thanks @attachmentgenie  I assume you're loading mcrypt via PECL for php 7.x?

**Comment by attachmentgenie** [comment]
> Thanks @attachmentgenie I assume you're loading mcrypt via PECL for php 7.x?

unfortunately yes (rpm that packages the pecl package), untill i have some time to turn it into something using libsodium

**Pull request merged**
