### PR TITLE
Correct spelling mistakes

### PR DESCRIPTION
**Pull request by EdwardBetts**

### CODE REVIEW

**Comment by RussH** [comment]
Thank you @EdwardBetts !

**Comment by shantadam** [comment]
Hi Russ,

Just noticed the merge. While at it, should we also have it available on the Test PHP 7 branch as well?

Regards,
Shant Adam


On Sep 5, 2019, at 11:27 AM, RussH <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you @EdwardBetts<https://github.com/EdwardBetts> !

**Comment by RussH** [comment]
Hi @shantadam  as this was a spelling mistake I thought it could live in master. we'll stick with test-php-7 for now, then merge that back into development, then development back to master for a release.. at least that's the plan. Give me a shout in the opencats slack if it seems like a problem?

**Comment by shantadam** [comment]
All good, Russ. Thanks.

Regards,
Shant Adam

**Pull request merged**
