### PR TITLE
Datagrid filters ui refactor and bugfixes

### PR DESCRIPTION
**Pull request by mlespiau**
The following PR contains a refactor in the UI filters for datagrids and also contains two bugfixes and functional tests.

I've created a 2 minutes quickcast to demo the issues that were fixed in this PR: http://quick.as/jnxwtxw3g

Now I'm working on a similar refactor but in the datagrid backend. The end goal is to be able to add new filters without doing obscure string parsing and serialisation to communicate the filter option and values between the UI and the PHP backend.

### CODE REVIEW

**Comment by RussH** [comment]
@mlespiau the Travis CI build checks failed for this ?

**Comment by mlespiau** [comment]
Yes, I'm investigating. Seems like a problem with the selenium docker
container but I can't reproduce on my local :(. I guess we can make
progress with the code review. I'll try to fix this today.

**Comment by mlespiau** [comment]
It was a silly mistake in the code that enables the tests, fixed and all green now! :)

**Comment by RussH** [comment]
Great.. thanks for sorting that!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the O2 network.                                                                                                                                                                                                                From: Matias LespiauSent: Friday, 15 July 2016 21:03To: opencats/OpenCATSReply To: opencats/OpenCATSCc: RussH; CommentSubject: Re: [opencats/OpenCATS] Datagrid filters ui refactor and bugfixes (#87)It was a silly mistake in the code that enables the tests, fixed and all green now! :)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request merged**
